"""Helpers for tracking files generated by tool executions."""

from __future__ import annotations

import mimetypes
import os
import time
from pathlib import Path
from typing import Any


IGNORED_ARTIFACT_DIRS = {
    ".cache",
    ".git",
    ".idea",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "bin",
    "dist",
    "env",
    "envs",
    "node_modules",
    "obj",
    "site-packages",
    "target",
    "venv",
}

TEXT_EXTENSIONS = {
    ".bat",
    ".c",
    ".cmd",
    ".conf",
    ".cpp",
    ".cs",
    ".css",
    ".csv",
    ".go",
    ".h",
    ".hpp",
    ".ini",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".log",
    ".md",
    ".mjs",
    ".py",
    ".rb",
    ".rs",
    ".scss",
    ".sh",
    ".sql",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".vue",
    ".xml",
    ".yaml",
    ".yml",
}

CODE_EXTENSIONS = {
    ".bat",
    ".c",
    ".cmd",
    ".cpp",
    ".cs",
    ".css",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".jsx",
    ".mjs",
    ".py",
    ".rb",
    ".rs",
    ".scss",
    ".sh",
    ".sql",
    ".ts",
    ".tsx",
    ".vue",
}

TRACKED_ARTIFACT_EXTENSIONS = TEXT_EXTENSIONS | {
    ".doc",
    ".docx",
    ".gif",
    ".html",
    ".htm",
    ".jpeg",
    ".jpg",
    ".pdf",
    ".png",
    ".ppt",
    ".pptx",
    ".webp",
}


def preview_kind_for_path(path: str | Path) -> str:
    suffix = Path(path).suffix.lower()
    if suffix in CODE_EXTENSIONS:
        return "code"
    if suffix == ".md":
        return "markdown"
    if suffix in {".html", ".htm"}:
        return "html"
    if suffix == ".pdf":
        return "pdf"
    if suffix in {".doc", ".docx"}:
        return "word"
    if suffix in {".png", ".jpg", ".jpeg", ".gif", ".webp"}:
        return "image"
    if suffix in TEXT_EXTENSIONS:
        return "text"
    return "binary"


def artifact_metadata(path: str | Path, *, cwd: str | Path | None = None) -> dict[str, Any]:
    resolved = Path(path).expanduser().resolve()
    stat = resolved.stat()
    mime_type, _ = mimetypes.guess_type(str(resolved))
    relative_path = ""
    if cwd is not None:
        try:
            relative_path = str(resolved.relative_to(Path(cwd).expanduser().resolve()))
        except ValueError:
            relative_path = ""
    return {
        "path": str(resolved),
        "name": resolved.name,
        "relative_path": relative_path,
        "extension": resolved.suffix.lower(),
        "mime_type": mime_type or "application/octet-stream",
        "size": stat.st_size,
        "updated_at": stat.st_mtime,
        "preview_kind": preview_kind_for_path(resolved),
    }


def build_artifact_list(paths: list[str | Path], *, cwd: str | Path | None = None) -> list[dict[str, Any]]:
    artifacts: list[dict[str, Any]] = []
    seen: set[str] = set()
    for path in paths:
        try:
            resolved = str(Path(path).expanduser().resolve())
            if resolved in seen or not Path(resolved).is_file():
                continue
            seen.add(resolved)
            artifacts.append(artifact_metadata(resolved, cwd=cwd))
        except OSError:
            continue
    return artifacts


def snapshot_artifact_candidates(root: str | Path, *, max_files: int = 8000) -> dict[str, tuple[int, int]]:
    """Return a lightweight mtime/size snapshot for likely artifact files."""
    resolved_root = Path(root).expanduser().resolve()
    snapshot: dict[str, tuple[int, int]] = {}
    scanned = 0
    for dirpath, dirnames, filenames in os.walk(resolved_root):
        dirnames[:] = [
            name for name in dirnames
            if name not in IGNORED_ARTIFACT_DIRS and not name.startswith(".git")
        ]
        for filename in filenames:
            if Path(filename).suffix.lower() not in TRACKED_ARTIFACT_EXTENSIONS:
                continue
            path = Path(dirpath) / filename
            try:
                stat = path.stat()
            except OSError:
                continue
            snapshot[str(path.resolve())] = (stat.st_mtime_ns, stat.st_size)
            scanned += 1
            if scanned >= max_files:
                return snapshot
    return snapshot


def changed_artifacts(
    before: dict[str, tuple[int, int]],
    after: dict[str, tuple[int, int]],
    *,
    cwd: str | Path,
    max_artifacts: int = 20,
) -> list[dict[str, Any]]:
    changed_paths = [
        path for path, state in after.items()
        if before.get(path) != state
    ]
    changed_paths.sort(key=lambda item: after[item][0], reverse=True)
    return build_artifact_list(changed_paths[:max_artifacts], cwd=cwd)


def now_timestamp() -> float:
    return time.time()
